name: Windows CI

on:
 push:
   paths-ignore:
     - '**/README.md'
 pull_request:
   branches: [master]

jobs:
  build_and_test:
    name: OuiSync Flutter App - Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Adding windows target (x86_64-pc-windows-gnu)
        run: rustup target add x86_64-pc-windows-gnu
      - name: Building OuiSync library
        run: |
         cd ouisync-plugin\ouisync
         cargo build --release -p ouisync-ffi
      - name: Generating Rust FFI bindings for the library, to be used in the OuiSync plugin.
        run: |
         cd ouisync-plugin\ouisync
         cargo run --bin bindgen

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.7.1'

      - name: Getting Flutter packages (App)
        run: flutter pub get

      - name: Getting Flutter packages (Plugin) and generating the Dart bindings for the OuiSync plugin (from the Rust FFI bindings for OuiSync library)
        run: |
         cd ouisync-plugin
         flutter pub get
         flutter pub run ffigen

      - name: Run tests
        env:
          OUISYNC_LIB: 'D:\a\ouisync-app\ouisync-app\ouisync-plugin\ouisync\target\release\ouisync_ffi.dll'
        run: |
          flutter test

      - name: Building EXE (x86_64-pc-windows-gnu)
        run: flutter build
